package com.example.crewportal.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.crewportal.data.repository.FlightRepository
import com.example.crewportal.data.repository.PreferencesRepository
import kotlinx.coroutines.launch

@Composable
fun SettingsScreen(
    flightRepository: FlightRepository,
    preferencesRepository: PreferencesRepository,
    onLogout: suspend () -> Unit
) {
    val scope = rememberCoroutineScope()
    val language by preferencesRepository.appLanguage.collectAsState(initial = "en")
    val ru = language == "ru"

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(if (ru) "Настройки" else "Settings", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold)

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(if (ru) "Язык" else "Language", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text(
                    if (ru) "Текущий язык интерфейса: русский" else "Current interface language: English",
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    Button(onClick = { scope.launch { preferencesRepository.setAppLanguage("en") } }) { Text("English") }
                    OutlinedButton(onClick = { scope.launch { preferencesRepository.setAppLanguage("ru") } }) { Text("Русский") }
                }
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(if (ru) "Приложение" else "Application", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("Crew Portal 1.6.8", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Ростер: синхронизация с порталом компании выполнена" else "Roster sync: Company Crew Portal synchronization successful", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Назначение борта: за 24 часа до вылета" else "Aircraft assignment: released 24 hours before departure", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Гейт / стоянка: за 3 часа до вылета" else "Gate / stand assignment: released 3 hours before departure", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Экипаж: формируется модулем планирования" else "Crew pairing: generated by company roster module", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Погода: aviationweather.gov" else "Weather source: aviationweather.gov", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Карта: OpenStreetMap / osmdroid" else "Map source: OpenStreetMap / osmdroid", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(if (ru) "Типы уведомлений" else "Notification Types", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text(if (ru) "Открыта регистрация" else "Registration window opened", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Назначен борт" else "Aircraft assignment released", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Изменения ростера и сообщения компании" else "Roster changes and operational messages", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Напоминания по документам" else "Qualification expiry reminders", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text(if (ru) "Рейс завершён и налёт обновлён" else "Flight completed and flight time updated", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Change Log — 1.6.8", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("• Added real-style THAI logo badge.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Route map markers now use A/B labels directly on the map.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Registered flight button now stays green after registration.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Added company contact directory.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Added Russian interface option in Settings.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Updated ICAO English record to Level 5, March 2026.", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Button(onClick = { scope.launch { flightRepository.reloadScheduleFromAssets() } }, modifier = Modifier.fillMaxWidth()) { Text(if (ru) "Синхронизировать с порталом компании" else "Synchronize with Company Portal") }
        Button(onClick = { scope.launch { flightRepository.simulateRosterChange() } }, modifier = Modifier.fillMaxWidth()) { Text(if (ru) "Имитировать изменение ростера" else "Simulate Roster Change") }
        Button(onClick = { scope.launch { onLogout() } }, modifier = Modifier.fillMaxWidth()) { Text(if (ru) "Выйти" else "Sign Out") }
    }
}
