package com.example.crewportal.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.crewportal.data.repository.FlightRepository
import com.example.crewportal.ui.theme.TextMuted
import kotlinx.coroutines.launch

@Composable
fun SettingsScreen(flightRepository: FlightRepository, onLogout: suspend () -> Unit) {
    val scope = rememberCoroutineScope()
    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text("Settings", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold)
        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Application", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("Crew Portal 1.6.6", color = TextMuted)
                Text("Roster sync: Company Crew Portal synchronization successful", color = TextMuted)
                Text("Aircraft assignment: released 24 hours before departure", color = TextMuted)
                Text("Gate / stand assignment: released 3 hours before departure", color = TextMuted)
                Text("Crew pairing: generated by company roster module", color = TextMuted)
                Text("Weather source: aviationweather.gov", color = TextMuted)
                Text("Map source: OpenStreetMap / osmdroid", color = TextMuted)
                Text("Airport database: local IATA/ICAO and UTC offsets", color = TextMuted)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Notification Types", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("Registration window opened", color = TextMuted)
                Text("Aircraft assignment released", color = TextMuted)
                Text("Roster changes and operational messages", color = TextMuted)
                Text("Qualification expiry reminders", color = TextMuted)
                Text("Flight completed and flight time updated", color = TextMuted)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Change Log — 1.6.6", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("• Removed map zoom buttons; pinch zoom remains available.", color = TextMuted)
                Text("• Monthly flight-time card now follows the current month.", color = TextMuted)
                Text("• Today’s Duty now shows only duties on the current date.", color = TextMuted)
                Text("• Added OFF duty blocks to Roster and Calendar.", color = TextMuted)
                Text("• Reserve duties now open a details page with time and hotel location.", color = TextMuted)
                Text("• Added THAI badge styling on flight cards.", color = TextMuted)
                Text("• Fleet cards now include aircraft age.", color = TextMuted)
                Text("• Added licenses, Class 1 medical certificate and recurrent qualification dates.", color = TextMuted)
                Text("• Added quick dark-theme switch above UTC toggle on Roster.", color = TextMuted)
            }
        }

        Button(onClick = { scope.launch { flightRepository.reloadScheduleFromAssets() } }, modifier = Modifier.fillMaxWidth()) { Text("Synchronize with Company Portal") }
        Button(onClick = { scope.launch { flightRepository.simulateRosterChange() } }, modifier = Modifier.fillMaxWidth()) { Text("Simulate Roster Change") }
        Button(onClick = { scope.launch { onLogout() } }, modifier = Modifier.fillMaxWidth()) { Text("Sign Out") }
    }
}
