package com.example.crewportal.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.crewportal.data.repository.FlightRepository
import com.example.crewportal.ui.theme.TextMuted
import kotlinx.coroutines.launch

@Composable
fun SettingsScreen(flightRepository: FlightRepository, onLogout: suspend () -> Unit) {
    val scope = rememberCoroutineScope()
    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text("Settings", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold)
        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Application", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("Crew Portal 1.6.7", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Roster sync: Company Crew Portal synchronization successful", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Aircraft assignment: released 24 hours before departure", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Gate / stand assignment: released 3 hours before departure", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Crew pairing: generated by company roster module", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Weather source: aviationweather.gov", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Map source: OpenStreetMap / osmdroid", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Airport database: local IATA/ICAO and UTC offsets", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Notification Types", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("Registration window opened", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Aircraft assignment released", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Roster changes and operational messages", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Qualification expiry reminders", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Flight completed and flight time updated", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface), modifier = Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Change Log — 1.6.7", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                Text("• Added THAI logo badge on flight cards.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• OFF roster blocks are no longer clickable.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Route map now labels A departure and B arrival; zoom buttons remain hidden.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Improved dark-theme readability across roster, calendar, fleet, weather and profile.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• METAR / TAF cards now use dark-theme friendly colors.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Added Refresh controls for roster and weather.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("• Expanded pilot license and qualification records.", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }

        Button(onClick = { scope.launch { flightRepository.reloadScheduleFromAssets() } }, modifier = Modifier.fillMaxWidth()) { Text("Synchronize with Company Portal") }
        Button(onClick = { scope.launch { flightRepository.simulateRosterChange() } }, modifier = Modifier.fillMaxWidth()) { Text("Simulate Roster Change") }
        Button(onClick = { scope.launch { onLogout() } }, modifier = Modifier.fillMaxWidth()) { Text("Sign Out") }
    }
}
